# Generated by Django 3.0.8 on 2020-07-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogposter',
            new_name='username',
        ),
    ]
