# Generated by Django 3.0.8 on 2020-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200718_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
