# Generated by Django 3.0.8 on 2020-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_followinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('likedby', models.CharField(max_length=64)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
